### ISSUE TITLE
Apple Silicon ARM64 Development

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WeVoteCordova#154]
Apple Silicon running on the DTK is in decent share for the "traditional" header offsets -- The Apple Silicon app running on the "Big Sur" desktop looks just like our app on an iPad, but with out the top line that shows cell signal strength, battery, and date and time.  As a result almost every header offset was different.  There is a new function `isAppleSilicon()` that is used to distinguish from the similar sized iPad display.

![Screen Shot 2020-10-01 at 6 52 45 PM](https://user-images.githubusercontent.com/6923653/94880276-50b91d80-0417-11eb-9e84-2b9d66265db0.png)

![Screen Shot 2020-10-01 at 6 57 34 PM](https://user-images.githubusercontent.com/6923653/94880531-0a17f300-0418-11eb-8e46-9c363e3d17e1.png)

**Comment by SailingSteve** [comment]
**TODO:**

- [ ] Signing in with Twitter/Facebook opens a tab in the Safari desktop browser instead of in the the App window.  If you still try to login in the Safari tab, you end up with a "ibsystem_kernel.dylib`mach_msg_trap: Thread 1: signal SIGCONT" unix (MaxOS) process crash that kills the app.
- [ ] Share to Twitter or Facebook do not work because they require a signing.  Sure to email works great, and copying the short link to the clipboard works.  The preview button opens a safari tab, hangs, but does not crash.
- [ ]  The Help button doesn't show up.
- [ ]  Sign in with Apple fails with `[core] No window got from UINSSharedApplicationDelegate`
- [ ] Ballotpedia (for example) opens in a Safari Desktop tab, but also opens an empty modal dialog with a Done button.

**Comment by SailingSteve** [comment]
![Screen Shot 2020-10-02 at 4 07 36 PM](https://user-images.githubusercontent.com/6923653/94976331-7a328180-04c9-11eb-9b74-8a3d8caa28b3.png)

**Comment by SailingSteve** [comment]
Done and released.
