### ISSUE TITLE
TODO: January 2018

### ISSUE THREAD

**Issue by SailingSteve** [wevote/WeVoteCordova#5]
An amazing amount of the App is working today in Cordova, maybe 95% of the functionality.  

Open issues:

- [ ] iOS Submission 

- [x] Android

- [ ] Facebook login (tough one)

- [x] Add an intermediate splash screen between the iOS screen and our index.html splash screen to avoid the white flash.

- [ ] Login by email, sends you off to browser land, it might be doable if you view your email on your phone.

Disabled:

- [ ] Re-enable Google analytics

- [ ] Re-enable "Ballot Location" in HeaderGettingStartedBar

- [ ] Re-enable all Facebook login 

- [ ] Re-enable the "Vote / Polling Location" button on the secondary header bar, since the frame isn't working in Cordova. 

Done:

- [x] oAuth redirects do not return to the Cordova app, they open a local WebApp instance in safari.  This will probably be similar to the oAuth work in WeVoteReactNative.

- [x] Re-enable "ReactPlayer" in About.jsx   I bet we need that iOS/React video player plug in.
- [x] Get rid of the two SafariViewController() views on Twitter Login
- [x] Test on various iPhone sizes in the simulator, and physical recent ones too.
- [x] The Cordova app does not use the full iPhone screen, for some reason it seems to be leaving the iOS menu space at the bottom as a black area, and a similar area at top.  It works as is, but looks weird.

- [x] It would be nice to figure out Chrome devtools debugging -- this works with React Native, and of course with our React WebApp.  The Apple tools are ok, but disappointing, and functionality is missing.

**Comment by SailingSteve** [comment]
Moved to:
Lower priority features that are disabled in Cordova #49
